version: '3'
services:
  socks5-build:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ghcr.io/accalina/socks5-build:1.0
    env_file: .env
    ports:
      - "1080:1080"
    restart: unless-stopped
